services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env # Esto carga autom√°ticamente el archivo .env en el contenedor
    environment:
      - DB_HOST=db-service # Sobrescribimos el host para que apunte al contenedor
    depends_on:
      - db-service

  db-service:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      # Mapeamos las variables del .env a las que Postgres espera internamente
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
