services:
  app:
    image: ${DOCKERHUB_USERNAME}/nest-api-auth:latest # Usamos la imagen de la nube
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db-service
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db-service
    networks:
      - nest-network

  db-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  pgdata:
